#!/bin/bash
## The script to download, rename and move the background and set the background

wget https://i.redd.it/29rztr2atai61.jpg
mv 29rztr2atai61.jpg /usr/share/backgrounds/virtualinsanityBG.jpg
gsettings set org.gnome.desktop.background picture-uri file://///usr/share/backgrounds/virtualinsanityBG.jpg
echo "This desktop..."
echo "Made of..."
echo "Virtual Insanity"
##
